# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               中年囈語
tagline:             
url:                 http://yowkee.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              yowkee
  url:               https://twitter.com/yowkee
  email:             ykwrite@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
